# file: wrangler.toml
# description: Cloudflare Workers configuration for crypto pricing API
# docs_reference: https://developers.cloudflare.com/workers/wrangler/configuration/

name = "crypto-pricing"
main = "dist/worker.js"
compatibility_date = "2024-11-06"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[site]
bucket = "./dist"

[env.production]
vars = { ENVIRONMENT = "production", LOG_LEVEL = "info" }

[env.development]
vars = { ENVIRONMENT = "development", LOG_LEVEL = "debug" }
